services:
  - type: web
    name: atom-edu-web
    env: python
    plan: free
    branch: main
    rootDirectory: .
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: 4
    healthCheckPath: /health/
    autoDeploy: true

  - type: postgresql
    name: atom-edu-db
    plan: free
    ipAllowList: []